// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flerxdkyxpkzwowafpqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZXJ4ZGt5eHBrendvd2FmcHFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTkzODYsImV4cCI6MjA2MDk5NTM4Nn0.nbMEzlOd7q1uWv4G-_vS5Ybu8GU-MKjo_PS1PYMpSjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);